on:
  pull_request:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "20 */2 * * *" # 12 times per day

jobs:
  benchmark-self-hosted-amd64:
    uses: ./.github/workflows/benchmark.yaml
    with:
      runs-on-hosted: self-hosted
      runs-on-architecture: amd64
