name: Network benchmark no-proxy

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */6 * * *" # 4 times per day
jobs:
  network-benchmarks-no-proxy:
    name: PS5 network benchmark no proxy
    runs-on: [network-test, noproxy]
    steps:
    - name: Librespeed cli
      if: ${{ always() }}
      run: |
        /home/ubuntu/librespeed/librespeed-cli

  network-benchmarks-proxy:
    name: PS5 network benchmark ps5 proxy
    runs-on: [network-test, proxy]
    steps:
    - name: Librespeed cli
      if: ${{ always() }}
      run: |
        wget https://github.com/librespeed/speedtest-cli/releases/download/v1.0.10/librespeed-cli_1.0.10_linux_amd64.tar.gz
        tar -xvzf librespeed-cli_1.0.10_linux_amd64.tar.gz
        ./librespeed-cli
