name: Test ARM

on: push

jobs:
  test-arm:
    name: job job
    runs-on: [self-hosted, ARM64]
    steps:
      - name: Test echo
        run: |
          echo "hello world"
      - name: docker
        run: |
          docker ps
      - name: python
        run: |
          python3 -m pip --version
